zbm-dev/zfsbootmenu

- bin/generate-zbm
- etc/zfsbootmenu/config.ini
- examples/kboot.conf
- examples/syslinux.cfg
Add in the ability to generate syslinux.cfg. This has been tested with syslinux/extlinux on x86_64 and with petitboot on POWER9 hardware.
> Basic syslinux support

- 90zfsbootmenu/module-setup.sh
- 90zfsbootmenu/zfs-chroot
- 90zfsbootmenu/zfsbootmenu-lib.sh
- 90zfsbootmenu/zfsbootmenu.sh
Don't worry, you can still create the pull request. Damn it.
> Set restore loglevel

- 90zfsbootmenu/zfsbootmenu-lib.sh
- 90zfsbootmenu/zfsbootmenu.sh
Implements a solution to #41 but needs a more testing before merging to master.
This also required reworking the kernel detection logic to avoid continually appending the same kernels to the list of available versions. (The kernel detection is a second commit to facilitate comparison and evaluation.)
> Rescan BEs and kernels with every iteration of menu loop

- 90zfsbootmenu/zfsbootmenu-lib.sh
Identify the parent dataset of the snapshot, then list all local and
received properties. Build an array of -o key=value sets, then apply at
clone creation time.
I squashed out the commit, but thank you @ahesford for tracking down the quoting issue.
Resolves #43
> Clone local/recieved properties

- 90zfsbootmenu/zfsbootmenu-lib.sh
- 90zfsbootmenu/zfsbootmenu.sh
This implements the logic outlined in #47 and seems to work as expected, but should be tested a bit more before merging. I take the kernel path identified from `draw_kernel` and drop the `/boot/` prefix to write the full kernel file name to the `org.zfsbootmenu:kernel` property of the associated BE.
> Initial support for setting default kernel versions

- 90zfsbootmenu/zfsbootmenu-lib.sh
Following the example of `95resume` in the standard `dracut` modules, I look for an active suspend image as a partition with type `suspend`, `swsuspend` or `swsupend`. If such a partition is detected, issue a dire warning and require positive confirmation from the user before importing a pool read-write when required.
When suspending to disk, a partition of type `swap` appears to have its type changed to one of these three (the type I'm seeing is `swsuspend`) to indicate the presence of an image.
> Initial support for resume guard

- 90zfsbootmenu/zfsbootmenu-lib.sh
Fixes #21.
When creating a `root=` kernel command-line, kexec_kernel now defers to a function that will attempt to determine the appropriate prefix to prepend to the ZFS dataset name. If the `org.zfsbootmenu:rootprefix` property is defined on the BE, that will be preferred; otherwise, if `/usr/lib/os-release` or `/etc/os-release` are available, those will be queried for OS identifiers will be searched for a preexisting default. If no suitable values are discovered, a default of "zfs:" is used.
**Needs testing**, especially on non-Void distributions.
> Allow root prefix to be customized for other distributions

- README.md
- grammar corrections
- clear up language
- fix up some formatting
> README: general clean up.

- 90zfsbootmenu/module-setup.sh
- 90zfsbootmenu/zfs-chroot
- 90zfsbootmenu/zfsbootmenu-lib.sh
- 90zfsbootmenu/zfsbootmenu.sh
> Helper cleanup

- testing/run.sh
I'm tired of manually adding multiple disks in test directories. As long as disks are suffixed with `-pool.img`, this will glob 'em all.
> Add option to auto-add all -pool.img disks in a test dir

- 90zfsbootmenu/zfsbootmenu-lib.sh
Pool checkpoint rewinding used a one-off fzf selection menu that was a bit difficult to use. This method has been normalized to use the same technique in resume_prompt().
While we're here, add color to resume_prompt.
> Use a common warning method

- 90zfsbootmenu/module-setup.sh
We want to keep identifying information in release binaries to a minimum, so just skip installing host-only files when building releases.
> Skip host-only files when release_build is defined

- docs/pod/zbm-efi-kcl.8.pod
- releng/pod2man.sh
Patterned after the `zbm-kcl` man page.
> Add minimal man page for zbm-efi-kcl

- releng/docker/image-build.sh
- releng/docker/zbm-build.sh
- zbm-builder.sh
- Allow container images to include custom Void packages via image-build.sh
- Allow container instances to include custom Void packages via zbm-build.sh
- Allow specification of custom Void packages and volume mounts via user-facing zbm-builder.sh
This can be used, *e.g.*, to build a custom dropbear-enabled image via `zbm-builder.sh` with a few simple modifications to the build directory used in the containerized build process:
1. Create the file `cmdline.d/dracut-network.conf` with contents `ip=dhcp rd.neednet=1`
2. Create the directory `dropbear` and place desired OpenSSH host keys (public *and* private) as well as an `authorized_keys` file with keys allowed to connect to ZBM
3. Create the file `dracut.conf.d/dropbear.conf` with contents, *e.g.*,
```sh
add_dracutmodules+=" crypt-ssh " …
```
> Enhance configurability of containerized builds

- zfsbootmenu/lib/zfsbootmenu-lib.sh
`column_wrap` executes in ~15ms from master and ~19ms with these changes (under the flamechart profiler).
> Center key bind text on horizontal layout fzf screens

- etc/zfsbootmenu/recovery.conf.d/recovery.conf
- releng/docker/image-build.sh
No other viable packaged SSH clients on Void - so this one is it.
> Include the OpenSSH client in recovery images

- releng/tag-release.sh
Tested as far as I could get locally. `zbm-efi-kcl` is successfully copied to the assets directory and signed.
> Add zbm-efi-kcl to release assets

- docs/conf.py
- releng/tag-release.sh
> releng/tag-release.sh: update docs/conf.py on release

- docs/guides/general/container-building.rst
- docs/guides/general/container-example.rst
- docs/guides/general/remote-access.rst
- docs/index.rst
Still getting used to RST and might need some help.
> docs: update container docs, unify with wiki content

- .github/workflows/docs.yml
- docs/CHANGELOG.md
- docs/Makefile
- docs/conf.py
- .github/workflows/docs.yml: add workflow to check links in docs
- docs/: make linkcheck pass
the current `linkcheck_ignore`s are for places where the link checker couldn't find the anchors used
> docs: check links in PRs/pushes to docs/

- docs/guides/_include/configure-gen-zbm.rst
- docs/guides/_include/setup-esp.rst
- docs/guides/_include/zbm-setup.rst
- docs/guides/debian/single-disk-uefi.rst
- docs/guides/fedora.rst
- docs/guides/fedora/_include/distro-install.rst
- docs/guides/fedora/_include/early-prep.rst
- docs/guides/fedora/_include/efi-boot-method.rst
- docs/guides/fedora/_include/reset-resolv.rst
- docs/guides/fedora/_include/zbm-install-deps.rst
- docs/guides/fedora/_include/zbm-install.rst
- docs/guides/fedora/_include/zfs-config.rst
- docs/guides/fedora/single-disk-detached-uefi.rst
- docs/guides/fedora/single-disk-uefi.rst
- docs/guides/void-linux/single-disk-detached-uefi.rst
- docs/guides/void-linux/single-disk-syslinux-mbr.rst
- docs/index.rst
Work-in-progress Fedora installation guide.
Current issues:
* ~`auditd` in the booted BE isn't starting correctly, for some unknown reason~
* ~`dhclient eno1` won't start in the booted BE due to a permissions issue on `/run` - this could be normal behavior when starting it directly on Fedora.~
> docs/guides/fedora/: initial Fedora 37 guides

- docs/Makefile
the rustification of zbm begins
> docs/Makefile: add target for running make serve repeatedly

- releng/tag-release.sh
- testing/helpers/zbm-populate.sh
- zbm-builder.sh
- zfsbootmenu/install-helpers.sh
Easier to read, easier to write. I think I found them all via `grep`.
> Perform case statements against lower-cased strings

- docs/guides/fedora/_include/zbm-install-deps.rst
- docs/guides/fedora/_include/zfs-config.rst
- docs/guides/fedora/uefi.rst
This guide will need to be re-tested to check if anything else has changed / broken / whatever.
> docs/guides/fedora: update to Workstation 38

- dracut/module-setup.sh
- etc/zfsbootmenu/recovery.conf.d/recovery.conf
- etc/zfsbootmenu/release.conf.d/common.conf
- releng/rst2help.sh
- zfsbootmenu/help-files/132/zbm-kcl.8.ansi
- zfsbootmenu/help-files/52/zbm-kcl.8.ansi
- zfsbootmenu/help-files/92/zbm-kcl.8.ansi
- zfsbootmenu/install-helpers.sh
* Add ca-certs to recovery image, so cURL can connect over HTTPS
* Add sgdisk to recovery image
* Add zbm-kcl / zbm-kcl.8 documentation to release and recovery images
Closes #400
> release/recovery: add tools to images

- docs/man/dist/man7/zfsbootmenu.7
- docs/man/zfsbootmenu.7.rst
- dracut/module-setup.sh
- initcpio/install/zfsbootmenu
- zfsbootmenu/install-helpers.sh
I'm still working on this and haven't tested anything, but this should close #427.
> dracut, initcpio: make libgcc_s search universal

- releng/docker/image-build.sh
A new `-r` argument to `image-build.sh` allows the specification of (at most one) local directory that will be mounted to `/pkgs` when preparing the container image. This allows, *e.g.*, a local test version of ZFS just by specifying
./releng/docker/image-build.sh -r /path/to/host/repo zbm-builder:$(date '+%Y%m%d')
This isn't (yet?) exposed in `releng/make-binary.sh` or `releng/tag-release.sh`. On the one hand, this is a special-enough use case that we can require a manual build of the container image (because `make-binary.sh` will use an existing container image that matches the desired tag) to use the feature. On the other hand, I'm open to ideas on how to expose this up the chain.
While I was at it, I fixed the `-headers` cleanup so the container image won't hang on to …
> releng/docker/image-build.sh: REPO MADNESS

- releng/docker/image-build.sh
- Add Void Fastly mirror by default, unless user specifies a web repo
- Add a `-k` option to allow custom selection of kernels added to image
> releng/docker/image-build.sh: improve repo and kernel selection

- zfsbootmenu/lib/zfsbootmenu-lib.sh
When fzf supports a border label (>= 0.35.0), show the current sort key that is being used to sort the list. This is only relevant on the main BE selection screen and the Snapshot selection screen. If fzf does not support a border label, fall back to legacy behavior of not showing the value anywhere.
https://asciinema.org/a/xfK6RvvJRGYLThSkMJgxhnJy0
> zfsbootmenu-lib: show sort key where needed

- docs/guides/general.rst
- docs/guides/general/tailscale.rst
mkinitcpio only because I don't know of any dracut tailscale modules
> docs/guides/general/tailscale: add tailscale integration guide

- docs/guides/general/tailscale.rst
not as good as dropbear, IMO, but worth mentioning I guess
> docs/guides/general/tailscale: mention tailscale ssh

- zfsbootmenu/bin/zfsbootmenu
- zfsbootmenu/lib/zfsbootmenu-core.sh
- zfsbootmenu/lib/zfsbootmenu-ui.sh
- zfsbootmenu/libexec/zfsbootmenu-preview
Honestly, I thought I merged this one long ago.
> zfsbootmenu/*: tab-delimit kernel lists for boot environments

- docs/guides/fedora/_include/live-environment.rst
- docs/guides/fedora/_include/zfs-config.rst
- docs/guides/fedora/uefi.rst
This needs to be tested, but hopefully it "just works".
> docs/guides/fedora/: update to Workstation 39

- docs/_static/custom.css
> docs/_static/custom.css: fix tab display in dark mode

- releng/docker/build-init.sh
The moving target that is Void may make some additional packages uninstallable when running the build container with `-p <pkg>`. Even when this is not the case, users may wish to update packages in the container before building a new ZBM image. (This may be useful, for example, to test new versions of key tools.) A new `-u` argument to the container entrypoint can trigger an XBPS update in the container before images are built or other packages are installed.
Generally, container images lack kernel headers, dkms and other build tools, so updating kernel and zfs packages will result in missing kmods for the updated kernels. Therefore, the default update behavior is to hold all kernel and zfs packages. Adding a second `-u` will force a "full" update, which will allow the kernel and zfs …
> releng/docker/build-init.sh: add an option to update packages

- Makefile
this is similar to many other projects that are install-only, like xtools
> Makefile: make zbm-release the default action

- docs/guides/fedora/_include/live-environment.rst
- docs/guides/fedora/_include/zfs-config.rst
- docs/guides/fedora/uefi.rst
Tested this last night, only required minor changes.
> Update Fedora guide to Workstation 40

- releng/Makefile
I think these are all of the packages needed for the scripts in `releng/`
> releng: add Makefile to install Void deps

- releng/make-binary.sh
We can simplify container introspection by just grabbing the kernel series rather than the specific version available, and then let `generate-zbm` in the container work its globbing magic to select the highest matching version. This also makes it easy to make prettier output names that are descriptive without being too detailed.
Output names are now things like
zfsbootmenu-release-x86_64-v3.0.0-linux6.12.EFI
zfsbootmenu-recovery-x86_64-v3.0.0-linux6.6.tar.gz
> releng/make-binary.sh: use globs for kernel versioning, improve output file names
