90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu-parse-commandline.sh, 90zfsbootmenu/zfsbootmenu.sh
By default, pools are now imported read-only. Because of this safety check, cloning a snapshot will fail. In the `clone_snapshot` function, we now do the following:
Check if the pool is read-only. If it is:
export the pool
toggle the readonly option in import_args
import the pool
if needed, reload encryption keys
The `key_wrapper` function was created to be a one-stop call to check if keys are needed for a fileystem, and to load them via file or prompt as required. This is used in a few different places now, and cleans up a bit of repeated logic.
The module argument `read_write` was added, with a default value of 0. If read_write=1 is passed on boot, pools will be imported in read-write mode.
=> RW clone fix

90zfsbootmenu/module-setup.sh, 90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu-parse-commandline.sh, 90zfsbootmenu/zfsbootmenu-preview.sh, 90zfsbootmenu/zfsbootmenu.sh
Instead of sequentially mounting each BE to the same mount point, sub directories of the form:
$TMP/$BE/mnt are created, where the boot environment is mounted.
Under that same directory structure, the default kernel and arguments are stored, as well as all detected kernels. These can be used by any function/tool, as they reside outside of the mountpoint.
A default bootfs option has been configured, ALT-D. This reads the selected environment and sets it as the bootfs value for the associated pool.
The main screen now has a preview window, showing the selected boot environment and the default kernel, as well as the kernel command line arguments. If the selected environment is the default bootfs, (default) is added to the preview line. 
Snapshot clones now auto-increment a 3-digit value …
=> Core update/feature bump

Makefile
The default mode for files copied by `install` is 0755. Configuration files in /etc/zfsbootmenu are installed with this mode by default. This PR changes the mode for configuration files to 0644.
=> Set proper file modes for configuration files.

90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu-preview.sh, 90zfsbootmenu/zfsbootmenu.sh
press alt-c on the main bootmenu screen to be prompted for a custom
kernel commandline. If this file is present, it's read by the preview
header. This kernel commandline is not persisted between reboots.
=> Add hot-key to accept custom commandline

90zfsbootmenu/zfsbootmenu-lib.sh, README.md, void-install.md
It bothers me to have `/etc/default/grub` to define command-line arguments when I don't have grub installed. Moving the arguments to the ZFS property `org.zfsbootmenu:commandline` is consistent with the reliance on `org.zfsbootmenu:kernel` for choosing a kernel version, and allows for nice default-and-override semantics that aren't realizable with a filesystem.
This should supersede issue #23, because this seems like a cleaner approach. I only wanted command-line inheritance because I didn't want the grub file. :)
=> Prefer ZFS property org.zfsbootmenu:commandline for command-line args

90zfsbootmenu/zfsbootmenu.sh
If `BE_SELECTED` is not cleared after entering the recovery shell, the shell will keep restarting upon exit.
=> Fix infinite loop in recovery console

90zfsbootmenu/zfsbootmenu.sh
Dracut provides options for handling console options (font, keymap, unicode/ASCII mode) in the `i18n` module (located in, *e.g.*, `/lib/dracut/modules.d/10i18n`). Inside the initramfs, the module installs the script `/lib/udev/console_init` to set these options according to the contents of `/etc/vconsole.conf`, which is populated by a `cmdline` hook that maps `rd.vconsole.*` kernel command-line options to values in this file (see `dracut.cmdline(7)` for more information). The module also installs a `udev` rule that will add a call to the `console_init` script as a dracut `initqueue` hook.
Unfortunately, execution of the `initqueue` hook is not guaranteed; the `initqueue` runloop continues until a number of predetermined "finish" conditions are satisfied. In `zfsbootmenu`, it seems the …
=> zfsbootmenu.sh: set console options before showing menu

bin/generate-zbm
This enables the user to add more configuration options in
/etc/zfsbootmenu/dracut.conf.d, such as the location of Secure Boot keys
to sign the unifiedEFI image.
=> [WIP] Use dracut to generate unifiedEFI images

90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu.sh
1. Move all snapshot cloning/duplication options the the `ALT+S` snapshot submenu.
1. Make send-recv duplication the default snapshot "promotion" behavior.
1. Make `ALT+X` in the snapshot submenu clone the selected snapshot and promote the clone.
1. Make `ALT+C` in the snapshot submenu clone the selected snapshot *without* promotion.
1. Remove `ALT+A` option from main menu; it never worked.
1. Ask for user-specified name for clones (promoted or not), like when using send-recv duplication.
1. Confirm that user-entered name for duplicates or clones does not conflict with an existing dataset.
1. Clean up `BE_SELECTED` handling in menu input loop.
=> Improvements to cloning and send-recv duplication

.github/workflows/ci.yml, README.md
`shellcheck` can help catch a number of small issues, and otherwise point out minor improvements. This commit adds an Actions config to execute `shellcheck` on a push to any branch. 
`modules-setup.sh` and `zfsbootmenu-parse-commandline.sh` have a number of problems that will need to be fixed before this can be merged, so we have a passing badge!
=> [WIP] Run shellcheck on any push

90zfsbootmenu/module-setup.sh, bin/generate-zbm
Instead of silently ignoring installation failures for critical kernel modules, we now check the return code from the install helper for key modules. If the module could not be installed, the error is trapped and an exit is forced to propagate this up to generate-zbm, which in turn exits before replacing or removing any initramfs/efi files.
Optional modules can still have installation attempts without erroring out the process.
**Broken on purpose**
```
bash-5.0# bin/generate-zbm --version test
Mounting /boot/efi
dracut-install: Failed to find module 'fake2'
dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.tJg9k4/initramfs --kerneldir /lib/modules/5.6.18_1/ -m fake2
dracut: Required kernel module 'fake2' is missing, aborting image creation!
Failed to create …
```
=> Trap kernel module installation failure

90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu.sh
When figuring out which snapshot to boot to fix a problem, it can be useful to know which files have changed. When browsing snapshots, there's now an ALT-D key handler which will call the `show_diff()` function. This function takes a single argument, the name of a snapshot. The pool and origin filesystem of the snapshot are determined via bash variable manipulation.  The diff shows all the changes between the snapshot selected and the current state of the fileystem.
To handle `zfs diff` not exiting when the `fzf` browser is exited early, the pid of the process is captured and then killed when fzf exits. The pool is mounted read-write because the `zfs diff` process requires it. 
`BE_SELECTED` is reset to 1, so that you return to the list of snapshots for that boot environmentt, instead of …
=> Show diff of snapshot against the current filesystem

90zfsbootmenu/zfsbootmenu-lib.sh
This draws the two line header on all of the sub-menus. This results in a seamless transition between screens - except on the diff screen. Until the `zfs diff` process starts to output lines, `fzf` doesn't draw the preview header.
=> Draw the preview header on kernel, snapshot and diff screens

90zfsbootmenu/zfsbootmenu-lib.sh, README.md
If a BE has `mountpoint=/`, setting `org.zfsbootmenu:active=off` will hide the BE from the boot menu; all other values will cause it to be shown. Conversely, if a BE has `mountpoint=legacy`, setting `org.zfsbootmenu:active=on` will cause the BE to be shown in the boot menu; all other values will prevent its display.
The idea is to allow different BEs to mount each other from `fstab`, which will not work unless `mountpoint=legacy`. This is useful, for example, if one has glibc and musl BEs and wishes to use one as a chroot from the other. The addition of `org.zfsbootmenu:active` provides a way to signal that `legacy`-mounted datasets should be scanned for kernels; otherwise we would have to scan every `legacy` dataset indiscriminately. Since I've added this property, allowing …
=> Initial support for org.zfsbootmenu:active visibility

90zfsbootmenu/zfsbootmenu-lib.sh, bin/generate-zbm
The dracut module now looks for a much broader range of acceptable names in pairs of kernels and initramfs/initrd images it will identify in boot environments. These improvements should allow zfsbootmenu to properly identify BEs from Arch Linux and its derivatives that do not include proper version information in kernel naming.
The `generate-zbm` script now accepts the `--kver` argument that should allow image creation on systems like Arch Linux where the version number cannot otherwise be reliably detected. This should fix #20. The `--prefix` argument is an added bonus that allows the prefix of the output zfsbootmenu components or UEFI bundle to be specified, which can improve handling in some (imagined) cases where kernel naming is even more severely broken than on Arch.
**Note**: this …
=> Improve kernel/initramfs detection in dracut module, support unversioned kernels in generate-zbm

bin/generate-zbm
Add an optional parameter to safeCopy:
0: disable cloning the mtime/atime of the source file to the dest file
1: enable cloning the mtime/atime of the source file to the dest file
(default action if no parameter is provided).
This allows newly created files to have the their timestamp reset for
correct ordering in rEFInd, while older files that are moved to be
backups keep their dates.
=> Fix rEFInd ordering problems

90zfsbootmenu/module-setup.sh, 90zfsbootmenu/zfsbootmenu-parse-commandline.sh
Various binaries were added over the last year, and some were no longer needed. Those binaries that were not referenced in any file in 90zfsbootmenu were removed.
Other binaries (ip, df, etc) are not explicitly needed for the operation of the module. These should be optionally installed via a so-called 'recovery mode' configuration file.
The cut binary was only used to manipulate a hostid. Those routines were switched to bash string manipulation methods.
=> Prune everything not explicitly needed

90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu.sh
- On the main boot menu screen, add a hook for ALT+P which shows a list
of discovered/imported pools.
- On the pool health screen, add key shortcuts for Rewinding a
checkpoint or Deleting a checkpoint. Since the fzf/sk header is a
static string at the bottom of the menu, it is shown regardless of a
pool checkpoint being present or not.
- If a checkpoint is to be deleted, use fzf to prompt the user Yes/No -
defaulting to No. The pool is re-imported read/write and then the
checkpoint is deleted.
- If a checkpoint is to be rewound, use fzf to prompt. The since a
rewind operation has to take place on pool import, export the pool and
then set the --rewind-to-checkpoint flag on the zpool import.
- set_rw_pool() does double duty - it guards against importing the pool
if a resume image is found, …
=> Add support for pool status and checkpoints

tests/.gitignore, tests/README.md, tests/chroot.sh, tests/run.sh, tests/setup.sh
* `sudo ./setup.sh`
1.  Creates a 1GB RAW image file
2.  Attaches it to the `loop0` loopback device
3. Creates a GPT label, and a ZFS pool named `ztest`
4. Installs Void base-minimal onto the pool
5. Configures the OS, sets the bootfs, and sets the root password to `zfsbootmenu`
* `./run.sh`
The following defaults can be set to a local default in `.config`:
```
DRIVE="format=raw,file=zfsbootmenu-pool.img"
INITRD="initramfs-bootmenu.img"
MEMORY="2048M"
SMP="2"
DISPLAY="gtk"
APPEND="loglevel=7 timeout=5 zfsbotmenu:POOL=ztest"
```
`run.sh` optionally takes a `-a` argument to override the kernel command line for ZFSBootMenu (`APPEND`).
=> [WIP] Enable the testing of changes in QEMU for rapid development/debugging

90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu-preview.sh, 90zfsbootmenu/zfsbootmenu.sh
`find_kernel_args` has been split into `preload_be_cmdline` and `load_be_cmdline`. The `preload_be_cmdline` function reads command-line arguments from a ZFS filesystem or the `/etc/default/{zfsbootmenu,grub}` files therein and stores the command line to `${BASE}/${BE}/cmdline` for a currently selected boot environment `${BE}`.
The `load_be_cmdline` only prints the contents of `${BASE}/cmdline` if it exists; otherwise, it will attempt to load the contents of `${BASE}/${BE}/cmdline` if that file exists (falling back to some generic default when the file does not exist) and attempt to remove any `resume` parameters and add a `noresume` parameter if a pool was mounted read-write in noresume mode.
Tested lightly in the new qemu testbed, with manual addition of a `noresume` trigger from an …
=> Simplify handling of BE command lines, use in previews

90zfsbootmenu/module-setup.sh, 90zfsbootmenu/zfsbootmenu-input.sh, 90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu.sh, testing/run.sh
Globally disable ctrl-c in /bin/zfsbootmenu by pointing it to an emptyhandler. Inside a subshell, unset the empty handler and then invoke zfsbootmenu-input with a single quoted argument; the pre-filled line that the user can edit. If ctrl-c is detected here, the script kills itself. Otherwise, it echos the line the user entered.
It is up to the caller to determine how to handle an empty response.
=> Allow ctrl-c to be used during user input

testing/.gitignore, testing/run.sh, testing/setup.sh
If `dracut` is run from the directory which contains files usually installed in `/usr/lib/dracut`, `dracut --local` seems to work.
=> testing: clone all of dracut installation to support local mode

90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu-preview.sh, 90zfsbootmenu/zfsbootmenu.sh
Add an alt-w helper to the main screen to set a pool r/w
Show r/o or r/w in the preview header for a selected pool (extracted from a BE)
=> Read-only helpers

90zfsbootmenu/module-setup.sh
The dracut module in ZFS < 2.0 produces initramfs images with all-zero hostid files on musl systems, regardless of the contents of /etc/hostid on the host. In ZFS >= 2.0, the dracut module respects the contents of /etc/hostid when possible, and will otherwise create a new /etc/hostid only if the hostid(1) program returns a non-zero value. (NB: to the ZFS kmods, a non-existent /etc/hostid is equivalent to a file containing all zeros.)
To minimize the possibility of import failures, ZFSBootMenu should try hard to replicate the behavior of whichever version of ZFS is creating initramfs images.
The version comparison here should be considered deprecated and removed once ZFS >= 2.0 has had sufficient time to overtake prior versions in popularity.
=> Fall back to legacy hostid creation for ZFS < 2.0

90zfsbootmenu/module-setup.sh, 90zfsbootmenu/zfsbootmenu-countdown.sh, 90zfsbootmenu/zfsbootmenu-exec.sh, 90zfsbootmenu/zfsbootmenu-parse-commandline.sh
It'd be nice to have the ability to see what is on the filesystem, what processes are running, etc in a running initramfs no matter where we are in ZFSBootMenu. Enter `tmux`. Set `zbm.tmux=1` on the ZBM KCL and build the initramfs with [dracut-tmux](https://github.com/zbm-dev/dracut-tmux) and /bin/zfsbootmenu will be launched in `tmux`. This has the added benefit of enabling job control for all processes launched under tmux.
I've moved anything considered 'setup' from `zfsbootmenu-countdown.sh` to `zfsbootmenu-exec.sh` so that whatever is launched (tmux, or zfsbootmenu-countdown) is started with the correct serial terminal size, environment variables, etc.
This requires someone to doubly opt in - both by explicitly enabling the `dracut-tmux` module and by setting the right KCL argument. …
=> Enable TMUX to support debugging efforts

90zfsbootmenu/module-setup.sh, 90zfsbootmenu/zfsbootmenu-exec.sh, 90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu-parse-commandline.sh, 90zfsbootmenu/zfsbootmenu.sh, 90zfsbootmenu/zlogtail.sh
Before I continue any further with adding zdebug/zinfo logging throughout the code base, I'd like to get a second set of eyes on the work as it stands.  The `zdebug` function generates log lines at a debug level in the kernel ring buffer:
```
2020-12-08T22:24:02,974442+00:00 ZBM:/libexec/zfsbootmenu-countdown[404]:import_pool(): read_write unset
2020-12-08T22:24:02,974535+00:00 ZBM:/libexec/zfsbootmenu-countdown[404]:import_pool(): all_pools set: yes
2020-12-08T22:24:02,974606+00:00 ZBM:/libexec/zfsbootmenu-countdown[404]:import_pool(): zpool import arguments: -N -o readonly=on -a 
2020-12-08T22:24:03,229771+00:00 ZBM:/libexec/zfsbootmenu-countdown[404]:import_pool(): import process return: 0
2020-12-08T22:24:06,779267+00:00 ZBM:/bin/zfsbootmenu[570]:be_has_encroot(): feature@encryption …
```
=> RFC/WIP: Add zlog() logging helper, along with debug-level logging

90zfsbootmenu/zfsbootmenu-countdown.sh, 90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu.sh, man/zfsbootmenu.7, pod/zfsbootmenu.7.pod
By setting `org.zfsbootmenu:keysource=<keysource>` on a BE or its parent, load_key will attempt to look for a key file specified by a `file://` keylocation relative to the filesystem specified by `<keysource>` and will cache this key within the initramfs. This allows single-sign-on for multiple BEs that have different encryption roots but a common keysource and keylocation.
Note: to prevent needless mounts, the cache is disabled when loading a key for automatic boot following the expiration of the countdown.
Pool layout (relevant portions):
```
NAME                                        MOUNTPOINT          ENCROOT                           KEYLOCATION                 ORG.ZFSBOOTMENU:KEYSOURCE
system                                      none                system …
```
=> Support configurable, opt-in caching of key files

90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu.sh
Now that 1.8.0 is out, let's mainline these deferrals.
Originally I reworked the main event loop in `zfsbootmenu.sh` to support an `Esc <=> Alt+R` swap, but that has been undone. However, I kept the simplifed event loop when I restored the original meaning of `Esc` and `Alt+R`.
=> Mainline the "deferred" branch

testing/run.sh
Aside from the hard dependency on `lsof`, this does what it should so that multiple testing instances can be run at once (though not with the same backing disks).
=> Test if :2222 is in use, increment until a free port is found

90zfsbootmenu/zfsbootmenu-parse-commandline.sh, pod/zfsbootmenu.7.pod, testing/run.sh
Move all ZFSBootMenu-specific arguments to the `zbm.*` argument space. Legacy values are still accepted in lieu of the new `zbm.` value, but will produce a warning on the kernel ring buffer. Timeout values have been expanded to work as follows:
zbm.timeout (or timeout) to set an explicit timeout option
OR zbm.show sets `menu_timeout=-1` to force the main menu
OR zbm.skip sets `menu_timeout=0` to skip the menu and directly boot `BOOTFS`
finally if none of these options are set, `menu_timeout=10` is set. 
The order of these tests might want to be flipped around to give precedence to `zbm.show` / `zbm.skip` - thoughts?
=> Namespace our KCL args, organize parsing

90zfsbootmenu/zfsbootmenu-help.sh, 90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu.sh
On the main screen and the snapshot screen, normalize the chroot key
combination to MOD-i (interactive chroot). Help documentation has been
updated for the main screen and added for the snapshot screen.
Additionally, document MOD-w and list the caveats for when it can be
used. This key is not documented in the header text - read the
documentation to understand what kind of foot-gun you're loading.
=> Change chroot keys, add help text

README.md
Add at least the ones in `cpanfile` -
those were the ones not present on my system.
=> README: Describe more Perl dependencies

90zfsbootmenu/zfsbootmenu-lib.sh
`genkernel` is often used to generate the initramfs on Gentoo.
An initramfs generated by genkernel accepts a ZFS root option
in the form of `root=ZFS=<dataset>`,
but does not accept `root=zfs:<dataset>`,
which is the default format for passing the root dataset
to the BE initramfs in `zfsbootmenu`.
For Gentoo BEs, make the default root prefix `root=ZFS=`,
which is accepted by both `genkernel`- and `dracut`-generated initramfs.
Users can still set the `org.zfsbootmenu:rootprefix` property
on `<pool>/ROOT` or the BE datasets to override the default.
Fixes: #136.
=> Use genkernel root prefix by default on Gentoo

90zfsbootmenu/zfsbootmenu-exec.sh, 90zfsbootmenu/zfsbootmenu-help.sh, 90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu-parse-commandline.sh, 90zfsbootmenu/zfsbootmenu.sh, man/generate-zbm.5, man/generate-zbm.8, man/zfsbootmenu.7, pod/zfsbootmenu.7.pod
On systems with a large number of boot environments or snapshots, sorting by name can be less than optimal. This PR adds the following:
* Allow `zbm.sort_key` to be set on the KCL, with `name`, `creation`, `used` considered valid sort keys
* Add a hook for `mod-o` on the BE and snapshot list screens, allowing the sorting method to be changed. Changing the sorting method on one screen changes it on the other, as well. This change persists until `zfsbootmenu.sh` is exited, at which point the selected method reverts to the default (`name`) or the method defined on the KCL.
Packing the sort methods into the global `zbm_sort` variable allows easy expansion of sort keys in the future. Simply add the list of valid keys to the array in parse-commandline.sh and it will be accepted and rotated …
=> Allow BE and snapshot sorting by different criteria 

90zfsbootmenu/zfs-chroot.sh, 90zfsbootmenu/zfsbootmenu-help.sh, 90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu-preview.sh
Move the helper functions from zfsbootmenu-help.sh:
* center
* colorize
`zfsbootmenu-preview.sh` had a lot of legacy code / procedures in it, before `zfsbootmenu-lib.sh` was as fleshed out as it is now. Clean up the usage / flow dramatically to use helper functions where possible.
`zfs-chroot.sh` now colorizes text when entering the chroot to add 37 pieces of flair to the output.
`timed_prompt`, `resume_prompt`, and the snapshot manipulation user input sections in `zfsbootmenu.sh` could possibly use an update to use `colorize` - but with the possible future use of `dialog`, that might be wasted effort. Thoughts?
Closes #115
=> Move more helper functions to -lib, cleanup scripts

90zfsbootmenu/zfs-chroot.sh, 90zfsbootmenu/zfsbootmenu-countdown.sh, 90zfsbootmenu/zfsbootmenu-exec.sh, 90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu-parse-commandline.sh, 90zfsbootmenu/zfsbootmenu-preview.sh, 90zfsbootmenu/zfsbootmenu.sh, 90zfsbootmenu/zlogtail.sh
This PR is an attempt to make logging play a more focused role in the ZBM ecosystem.  Various components would correctly catch and log an error through `zerror()`, but unless you know how to look for them, they were entirely hidden from view. As such, I attempted to meet the following goals:
* Where an error is critical, (kexec, duplicating a BE), show a prompt and log an error
* For all other error conditions, log an error with enough contextual information
* When an error is generated, show an indicator on the main screen
* Allow the error log to be viewed on any selector screen via `MOD-L`
In addition to the error log integrations, I made a pass through virtually every function in `zfsbootmenu-lib.sh`.  Where positional parameters are non-optional in a function call, a test for empty …
=> Logging lifecycle

90zfsbootmenu/zfs-chroot.sh, 90zfsbootmenu/zfsbootmenu-lib.sh
Seems to do the right thing in Arch/Ubuntu/Debian/Void chroots, and in the emergency shell.
=> Fix PS1 in arch/debian/ubuntu, set custom prompt in emergency shell

testing/run.sh
SSH'ing into a running VM was greatly improved with key additions to each BE. This should help even more by doing the following:
* Creates an SSH config file for the running VM that records the test name and configured SSH port forward
* Sets the remote username to `root`
* Host key checks are disabled, and the host key is no longer stored in `known_hosts`
With this in place, you can `ssh test.void` and have an immediate shell in the running test VM with out needing to accept any host keys, etc.
=> Create SSH includes for running VMs

90zfsbootmenu/zfs-chroot.sh, 90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu-preview.sh
* Show CWD in both the chroot and the emergency shell
* Show if a BE is encrypted and clean up how BE details are gathered/presented
=> Show if BE is encrypted, add path to chroot prompt

90zfsbootmenu/zfsbootmenu-countdown.sh, 90zfsbootmenu/zfsbootmenu-parse-commandline.sh
/lib/dracut/hooks/initqueue/finished is not created when rd.hostonly=0
is set. Additionally, if for some reason /dev/zfs is not present, a
dracut initqueue timeout would happen and you'd drop down to a limited
dracut shell. If instead we loop and check for /dev/zfs, we can fail to
a nicer recovery shell if it is absent.
https://pastebin.stratumzero.date/u/p/67d7b4adb6/stream
=> Remove dracut-ism, replace with an internal check

90zfsbootmenu/module-setup.sh, 90zfsbootmenu/zfsbootmenu-func-wrapper.sh, 90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu.sh
Instead of exiting the `fzf` snapshot browser, bind a key combination to the `execute[]` function in `fzf`, allowing you to keep your place in the list after viewing a diff.  zfs-chroot does not correctly function here, because it loses access to the backing TTY. Bash/dash will not write command output to the fzf alternate screen. Discovering the tty is easy for local consoles (control_term from -exec), but is much more difficult for connections over SSH.
=> Use fzf's execute[] function to render the zfs diff

90zfsbootmenu/zfsbootmenu-exec.sh, bin/generate-zbm
* Set a hostname in ZBM, so that when a pool is imported read/write, `(ZFSBootMenu)` is recorded instead of `(none)`
* In generate-zbm, warn if  `/sys/module/spl/parameters/spl_hostid`and the output of `hostid` do not match. This needs additional logic, since very few people set their hostid via `spl.spl_hostid`, ZFS's brain-dead logic of setting the sysfs entry to 0 by default makes it very challenging to detect what the source of truth actually is. Thoughts?
=> Set a hostname in ZBM, check if spl.spl_hostid matches /etc/hostid

90zfsbootmenu/zfsbootmenu-lib.sh
Long messages, particularly debug messages, were naively wrapped on the
screen width boundary. While this worked, all tracing information was
lost in the wrapped lines.
A log line prefix (based on the message level and dmesg capabilities) is
created and then prepended to all log lines after they've been wrapped.
Wrapping uses the screen width minus the prefix length minus the kernel
timestamp and fzf gutter.
Wrapped lines have '+   ' after the prefix to indicate that they're wrapped.
Non-wrapped lines have ': ' after the prefix.
=> Make sure wrapped log lines have a ZBM/tracing prefix

90zfsbootmenu/module-setup.sh, 90zfsbootmenu/zfsbootmenu-countdown.sh, 90zfsbootmenu/zfsbootmenu-exec.sh, 90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu.sh
`bash` login shells automagically source `/etc/profile` . 
* `dropbear` invokes bash as a login shell 
* `tmux` invokes bash as a login shell. 
* Switch the recovery shell to launch bash as a login shell.
Set a universal path, a generic terminal type, PS1, and source `/lib/zfsbootmenu-lib.sh`. Write all variables defined/controlled by the command line to this file. In both main ZBM entry point scripts (`zfsbootmenu.sh`, `zfsbootmenu-countdown.sh`),  source this file or source `/lib/zfsbootmenu-lib.sh` and warn that the environment file couldn't be sourced.
Any shell - tmux, recovery, or SSH should now have an identical environment.
=> Create and use /etc/profile everywhere

90zfsbootmenu/zfsbootmenu-lib.sh
If the SPL kmod has a non-zero `spl_hostid` parameter, nothing we write to `/etc/hostid` will have any effect. Forcing the module parameter to zero will cause ZFS to look to `/etc/hostid` for a value regardless of the initial state.
Needs testing to confirm that the parameter is writable on all systems, especially on the geriatric Ubuntu ZFS.
=> Force spl.spl_hostid=0 when matching hostid

90zfsbootmenu/zfsbootmenu-lib.sh
Any reference to `%{parent}` in `org.zfsbootmenu:commandline` will be replaced with the value of the same property on the parent filesystem (with parent references above recursively expanded), allowing easy specification of common options at a mutual parent of two BEs and overrides or additions of individual options per-BE. The value of `%{parent}` is always an empty string on a root filesystem.
This is not intended to be sophisticated, and `%{parent}` appearing within other words will be replaced regardless. The assumption is that `%{parent}` is unique enough and will not conflict with real KCL options, so dumb global replacement is sufficient.
Tested with the following setup:
```
NAME             ORG.ZFSBOOTMENU:COMMANDLINE
ztest            loglevel=4 spl_hostid=43b06f17 %{parent} …
```
=> Allow references to parent properties in org.zfsbootmenu:commandline

90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu-parse-commandline.sh
When console=ttyS0,1152800n8 is passed in to the kernel it does not directly translate to a /dev entry. Simply strip the ,value off of the console=x,y parameter and set that as our /dev entry.
When a pool import fails for some reason, log the text from the zpool import process at the debug log level.
=> Small quality of life improvements

90zfsbootmenu/help-files/134/kernel-management.pod, 90zfsbootmenu/help-files/54/kernel-management.pod, 90zfsbootmenu/help-files/94/kernel-management.pod, 90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu.sh, pod/online/kernel-management.pod
Add the `MOD+U` keyboard shortcut to allow 'unsetting' a pinned kernel, by way of inheriting the `org.zfsbootmenu:kernel` property. Under normal conditions (kernels pinned by ZBM), it'll simply remove the pin. The code to handle this was already present in the `set_default_kernel` function, it was just never glued to the user interface.
=> Add keyboard shortcut to remove pinned kernel

90zfsbootmenu/zfsbootmenu-parse-commandline.sh, pod/zfsbootmenu.7.pod
After a few months of testing, the `zbm.import_policy=hostid` and `zbm.set_hostid=on` have been tested enough to be the new default behaviors. Enable them and then update documentation to note that they're on by default.
=> Change ZBM defaults

90zfsbootmenu/zfsbootmenu-init.sh, 90zfsbootmenu/zfsbootmenu-parse-commandline.sh, 90zfsbootmenu/zfsbootmenu-preinit.sh
1. Allow `zbm.prefer=<pool>!` syntax for a *mandatory* preference; a mandatory poll must be imported before other pools will be attempted and ZBM continues.
2. Eliminate limits on import retries; the loop will continue indefinitely, displaying a countdown that the user can interrupt to drop to an emergency shell.
I need some help thinking through the logic to make sure the overhauled import loop will terminate properly, and this needs some real testing. My assumptions are:
- A preference was indicated, so the preferred pool *must* have succeeded; in this case, try again with no preference to pick up any other importables. (This should happen exactly once.)
- A preference was not indicated (because it never existed or we are retrying after dropping it); we are done because we have found at …
=> Improved pool imports

90zfsbootmenu/module-setup.sh, 90zfsbootmenu/zfsbootmenu-init.sh, 90zfsbootmenu/zfsbootmenu-parse-commandline.sh, 90zfsbootmenu/zfsbootmenu-preinit.sh
It was relatively easy to break ZFSBootMenu to the point that it was almost unrecoverable by passing an invalid `spl.spl_hostid` parameter. When an invalid parameter is set on the kernel command line it can't be overridden except by directly calling `insmod` with the full path to the kernel module and the fixed argument to the parameter.
Additionally, if `spl.spl_hostid` was passed into ZBM, incorrect default-hostid logic was applied because `spl_hostid` wasn't detected on the kernel command line, nor is `/etc/hostid` part of the release builds. Both forms of passing the hostid are now accepted and the argument is normalized when possible to an 8 character hex value. If it can't be normalized, `spl_hostid` is unset and the global default of `00bab10c` is used.
In `zfsbootmenu-init.sh`, …
=> Validate module parameters, verify that kernel modules are loaded

90zfsbootmenu/help-files/134/zfsbootmenu.7.pod, 90zfsbootmenu/help-files/54/zfsbootmenu.7.pod, 90zfsbootmenu/help-files/94/zfsbootmenu.7.pod, 90zfsbootmenu/zfsbootmenu-init.sh, 90zfsbootmenu/zfsbootmenu.sh, CHANGELOG.md, man/generate-zbm.5, man/generate-zbm.8, man/zfsbootmenu.7, pod/zfsbootmenu.7.pod, releng/make-binary.sh
* `insmod` doesn't gracefully fail if a module is already loaded. An initramfs generated on Arch loads `spl.ko` before our insmod attempts it, so check if it's not loaded and then load it.
* Split the filesystem/kernel/initramfs before the subkey handler under the kernel selection handler, so that it's available for pinning and unpinning kernels.
* Remove documentation for `zbm.import_retries` and regenerate the online help pages for that section.
* First pass at release notes for 1.10.
=> Release notes and fixes for 1.10

90zfsbootmenu/zfsbootmenu-init.sh, 90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu-preinit.sh, 90zfsbootmenu/zfsbootmenu.sh
To facilitate easily taking over a running ZFSBootMenu instance, regardless of where it is (ZFS password prompt, at the main menu, etc), the 'takeover' function has been created. 
In broad strokes, this works as follows:
* `/bin/zfsbootmenu` writes it's PID to `/zfsbootmenu/active`
* `/bin/zfsbootmenu` Installs a `USR1` handler that runs `exit 0`
* reads the pid out of `/zfsbootmenu/active` if it exists, sends it a `USR1` signal (which won't be processed until child processes are killed)
* Walks down the list of child PIDs for the active `/bin/zfsbootmenu` process; stops at the last child
* Kills the last child (typically either `fzf` or `zfs` password prompt)
* The `SIGUSR1` trap now executes, causing the running `zfsbootmenu` instance to exit
* On exit, `/zfsbootmenu/active` is removed …
=> Add easy 'takeover' helper

contrib/docker/Dockerfile, contrib/docker/zbm-build.sh, releng/make-binary.sh
Using podman to containerize the production of release assets avoids potential leakage of personal information. To support this, the containerized build script has been modified to separate the repo path at /zbm from a "build" directory (previously /zbm/contrib/docker was hard coded, now it's just the default choice). The releng script creates a temporary directory to serve as the "build" path, populates configs, and runs the build container with the current repo at /zbm and the temporary directory at /build. The outputs are copied as before, with the EFI executable standing alone and the kernel/initramfs components stored in a gzipped tarball.
If the releng script does not find the expected builder image (zbm-builder by default, but this can be passed as a second argument to the script), …
=> releng/make-binary.sh: use containerized image builds

90zfsbootmenu/module-setup.sh, 90zfsbootmenu/zfsbootmenu-init.sh, contrib/luks-unlock.sh, pod/zfsbootmenu.7.pod
Add in another hook - just after ZFS/SPL kmods are loaded but before anything else is attempted.
Add a proof-of-concept LUKS keystore script, intended to be used as an early setup hook.  This script will look for anything with a partition label of `KEYSTORE` and then verify that it is a block device with a LUKS header.  It then goes into a decryption prompt loop (broken by `ctrl-c`) to unlock the LUKS device. Upon successful unlock, the newly created `/dev/mapper/KEYSTORE` device is mounted to `/etc/zfs/keys` .  It's up to the end user to end user to to point any encryption root keys to be available on-disk at `/etc/zfs/keys` . 
This deserves some documentation in `README.md` and/or a wiki entry.
=> Early setup hooks, luks keystore contrib script

90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu.sh, pod/online/snapshot-management.pod
Some times it's helpful to be able to create a snapshot from the bootloader, outside of the OS. On the snapshot screen, there's now a MOD+N option to create a (N)ew snapshot. It rides along the coat-tails of most of the snapshot cloning/duplication logic, as that has checks for everything we also care about.
The `MOD+S` handler in `zfsbootmenu.sh` was growing quite large. It created a substantial number of global variables. A large part of the logic in this handler has been moved to a dedicated subroutine that does all of the appropriate space checks, user input prompts/checking, and then dispatches to the right snapshot manipulation function.
=> Snapshot creation, reorganization

90zfsbootmenu/zfsbootmenu-lib.sh, man/zfsbootmenu.7, pod/zfsbootmenu.7.pod
To allow completely custom overrides of the final boot process, teardown hooks are called with three variables in their environment:
- ZBM_SELECTED_BE: filesystem holding the selected boot environment
- ZBM_SELECTED_KERNEL: path to the kernel within the selected BE
- ZBM_SELECTED_INITRAMFS: path to the corresponding initramfs
This is motivated by a desire to allow Xen users to inject a load/kexec into the following stage, effectively making ZBM responsible for selecting dom0 without making ZBM understand Xen at all.
Closes #231.
=> Define BE selection variables in teardown hook environment

90zfsbootmenu/module-setup.sh, 90zfsbootmenu/zfsbootmenu-help.sh, 90zfsbootmenu/zfsbootmenu-lib.sh, 90zfsbootmenu/zfsbootmenu.sh, 90zfsbootmenu/zlogtail.sh, README.md
Skim hasn't seen a release since February 2021. It's starting to miss a
few features that we come to expect in fzf. Additionally, it has a few
rendering bugs / keybind issues that aren't easily resolved.
Removing skim support ends support for any platform not supported by Go,
but ZFS usage on those platforms isn't really common.
With all debug logging now running through the ztrace script, zlogtail
has been heavily simplified. It's now exclusively geared towards showing
warnning and error logs generated by the zwarn() and zerror() functions.
There is a `command -v fzf` test inside zfsbootmenu.sh - this can
possibly be removed. We test for fzf in module-setup.sh and critically
fail if it's missing.
=> Code removal / cleanup pass

bin/generate-zbm, contrib/esp-sync.sh, etc/zfsbootmenu/config.yaml, pod/generate-zbm.5.pod, testing/setup.sh
Since generate-zbm only knows how to manage one ESP, it can be a challenge to keep multiple redundant ESPs up-to-date on a system. To help with this, Global.PreHooksDir and Global.PostHooksDir can now bedefined to point to a directory of executable hooks. These are executed without any additional environment context or arguments in the order a shell glob returns them.
`rsync` can be restricted to only manage ZFSBootMenu files through something like this:
`rsync --delete-after -avpP --include=zfsbootmenu\* --exclude=\* /boot/efi/EFI/void/ /tmp/second-efi`
`contrib/esp-sync.sh` has been added as an example post hook.
=> Support early/late hooks in generate-zbm

90zfsbootmenu/zfsbootmenu-lib.sh
More than one `root=` entry will result in the last one taking precedence - likely breaking the ability to boot into an environment. So regardless of the source, suppress that option on the BE's KCL.
=> Regardless of the source, always suppress root=

90zfsbootmenu/module-setup.sh, 90zfsbootmenu/zfsbootmenu-preinit.sh, 90zfsbootmenu/zfsbootmenu-ready-chk.sh, 90zfsbootmenu/zfsbootmenu-ready-set.sh
The only hooks guaranteed to run in the dracut event loop are "finished" hooks. If none are installed (or they all indicate success up front), no other "initqueue" or "settled" hooks will ever run. This includes, e.g., console initialization.
Rather than force console initialization in zfsbootmenu-preinit.sh, let's add a initqueue/settled and initqueue/finished hooks that, respectively, touch and watch for a file. This will force at least one iteration of the entire event loop (except for "timeout" hooks, which may still be short-circuited). If we want, we can make the settled hook more sophisticated and use it to stand up the necessary pre-requisites.
On real hardware, I have confirmed that the initqueue/finished hook runs several times (after other hook categories are run, the finish …
=> Add "settled" and "finished" hooks to force dracut event loop to fire

testing/run.sh
If run.sh is invoked with -i or SSH_INCLUDE=1 is defined in
testing/.config, the wrapper script now does the following:
* Creates a dracut configuration file to enable crypt-ssh, listening on
port 22 with ~/.ssh/authorized_keys set as the dropbear authentication
ACL.
* Writes an SSH configuration file allowing ssh $test_environment to
transparently connect you to the running ZFSBootMenu instance on port
2222.
* Sets 'ip=dhcp rd.neednet' on the ZBM KCL.
If the option is not set, a dracut configuration file is written to omit
crypt-ssh.
The presence or absence of this flag does not control whether or not an
initramfs / EFI executable is generated.
=> Configure the initramfs for SSH access

.github/workflows/documentation.yml, releng/pod2help.sh, releng/pod2man.sh, releng/tag-release.sh
Both pod2man and pod2text default to 'die' on any POD formatting errors. We can leverage that by enabling `set -e` in `pod2man.sh` and `pod2help.sh`. `tag-release.sh` will now also trap any errors from either script and exit accordingly.
See https://github.com/zbm-dev/zfsbootmenu/runs/4584433141?check_suite_focus=true for an example of a forced failure.
=> Add a documentation linting stage

etc/zfsbootmenu/recovery.conf.d/recovery.conf, etc/zfsbootmenu/recovery.yaml, releng/docker/image-build.sh, releng/make-binary.sh, releng/tag-release.sh
Add in support for a `recovery` style image which contains additional tools and networking support. Right now the additions are pretty minimal:
* gdisk
* parted
* mkfs.vfat / mkfs.ext4
* curl
* efibootmgr
The zfsbootmenu dracut module already installs mbuffer, lsblk and blkid into release images.  The changes behind the scenes allow for an arbitrary number of image styles to be made, with release and now recovery being made. EFI images are all made from a common container that must have all of the tooling available for every image style, so attention must be given to additional files/modules automatically being pulled in to the wrong image. I'm not convinced it's worth the effort though to make a new container per release style though.
Once this is merged and a new ZFSBootMenu release is …
=> Generate release and recovery image builds

zbm-builder.sh
This is a simple script that wraps a container build to spit out custom images without requiring users install ZFSBootMenu and its dependencies locally. It bind-mounts the current directory as `/build` in the build container and uses defaults to create a `build` subdirectory that will contain output images.
If `hostid` or `zpool.cache` are found in the current directory, the script will use those. Otherwise, the system files will be copied (unless corresponding "disable" flags are specified) to the current directory for inclusion in the images.
Docker can be forced over podman if desired. A specific tag or general commit-like can be specified, so you can build arbitrary ZBM versions on command. The default build container is whatever is tagged "latest" on GHCR, but this can be overridden. …
=> zbm-builder.sh: add script to build custom images using GHCR container

bin/generate-zbm, cpanfile
The migration to a YAML configuration file happened 2020-07-29. We've carried support for migrating from the legacy INI format long enough.
=> generate-zbm: remove INI migration support

contrib/console-init.sh, etc/zfsbootmenu/recovery.conf.d/recovery.conf, etc/zfsbootmenu/release.conf.d/release.conf
Setting rd.hostonly=0 in the release and recovery images causes dracut to throw out the initqueue hooks that ZBM installs to force the event loop to fire at least once. As a result, the console is often not initialized before ZBM takes control. ZFSBootMenu early-setup hooks provide a convenient place to force the console initialization, allowing things like fonts and keymaps to be set before password prompts might appear.
=> Use an early-setup hook to force console init in release images

zfsbootmenu/install-helpers.sh, zfsbootmenu/lib/zfsbootmenu-core.sh, zfsbootmenu/lib/zfsbootmenu-lib.sh
`tr` is only used in a few places, so this drops it from images without busybox. Might or might not be worth it. 
What might be more important is the additional use of `shopt -s extglob`. I'm debating turning that on globally and just fixing the fallout from it - if there is any. Thoughts?
=> Replace 'tr' with bash string manipulation

contrib/luks-unlock.sh, zfsbootmenu/lib/zfsbootmenu-core.sh, zfsbootmenu/libexec/zfsbootmenu-init
The emergency shell now always shows:
```
emergency shell
type 'help' for online documentation
type 'exit' to return to ZFSBootMenu
```
If a specific message is passed in to the function, it is shown as follows:
```
emergency shell: contextual message
type 'help' for online documentation
type 'exit' to return to ZFSBootMenu
```
=> Make the emergency shell slightly fancy

zbm-builder.sh
Unlike Podman, Docker does not accept `.` or `./` as arguments for bind volumes at the command line. Modifying `zbm-builder.sh` to use `${PWD}` instead of `.` works for both Docker and Podman.
A typo in the default `config.yaml` causes `zbm-build.sh` to fail, fixed.
Currently, `zbm-build.sh` is hard-coded to pull the required tag from `zbm-dev/zfsbootmenu`. Adding this command line option allows builds using a local repository tree.
=> Bug fixes and use local repository option for zbm-builder.sh

docs/pod/online/main-screen.pod, zfsbootmenu/bin/zfsbootmenu, zfsbootmenu/help-files/132/main-screen.pod, zfsbootmenu/help-files/52/main-screen.pod, zfsbootmenu/help-files/92/main-screen.pod, zfsbootmenu/lib/zfsbootmenu-lib.sh
If `${BASE}/cmdline` exists, draw help text for reverting the KCL and attach the `alt-t` keybind to the main menu.
=> Add option to revert to default KCL via ctrl-t in draw_be

bin/zbm-efi-kcl
This is intended to be a stand-alone tool that can edit the `.cmdline` segment in the release and recovery EFI files.  It's marginally tested. Some of the 'cleanup' behavior might need to be modified or improved upon.
=> Basic EFI KCL editor

.github/workflows/build.yml, etc/zfsbootmenu/dracut.conf.d/omit-drivers.conf, etc/zfsbootmenu/recovery.conf.d/common.conf, etc/zfsbootmenu/recovery.conf.d/recovery.conf, etc/zfsbootmenu/release.conf.d/common.conf, etc/zfsbootmenu/release.conf.d/release.conf
This is tested only to the point that I prepared some release assets with `make-binary.sh` and did an `lsinitrd` on the release and recovery EFI bundles to confirm that some contents are expected.
=> Exploit common configurations for recovery/release images

README.md, docs/man/generate-zbm.5, docs/pod/generate-zbm.5.pod, etc/zfsbootmenu/config.yaml
Replaces `void` with `zbm` in the default esp path in configs and docs.
=> Make default efi path distro agnostic

zfsbootmenu/bin/zfs-chroot
Default/bare Alpine doesn't ship Bash by default. `/bin/sh` is a symlink to `/bin/busybox`, which is broken outside of the chroot.
=> Support busybox as /bin/sh in chroot

docs/pod/zfsbootmenu.7.pod, zfsbootmenu/help-files/132/zfsbootmenu.7.pod, zfsbootmenu/help-files/52/zfsbootmenu.7.pod, zfsbootmenu/help-files/92/zfsbootmenu.7.pod, zfsbootmenu/hook/zfsbootmenu-parse-commandline.sh, zfsbootmenu/libexec/zfsbootmenu-init
Extend the modifiers for `zbm.prefer` to include `!!`. The single `!` behavior is preserved, requiring the named pool to be imported. Once that import has completed successfully, no other imports are attempted. This has been minimally tested on a two pool test environment. There might be a nicer way to do the `!` / `!!` check, but this seems to work well enough.
=> Add support for !!, so ONLY the preferred pool is imported

zfsbootmenu/lib/zfsbootmenu-core.sh, zfsbootmenu/lib/zfsbootmenu-lib.sh
It's only a matter of time until a pool name conflicts with a file that we create in `/zfsbootmenu`. Moving the pool/dataset directory layout to `/zfsbootmenu/environments` puts them in a directory free of potential conflicts. A helper function, `be_location` has been added that returns the on-disk path for where a filesystem _should_ be mounted/live. This avoids having to manually construct this string when `mount_zfs` isn't in use.
=> Move boot environments to ${BASE}/environments/

dracut/module-setup.sh, etc/zfsbootmenu/dracut.conf.d/zfsbootmenu.conf
I don't know what broke the Debian and Ubuntu installations in https://github.com/zbm-dev/zfsbootmenu/issues/335 and I can't reproduce the issue in our testbed, even when I bump Ubuntu from "jammy" to "kinetic". However, clearly something has caused the affected images to link `/bin/sh` to dash. This breaks our KCL parsing, which is done in a sourced dracut hook before we explicitly exec into bash and take control.
The dracut `bash` module will force installation of `/bin/bash` and, if `/bin/sh` isn't linked, link to bash. Adding `bash` to the required dependencies of the ZBM dracut module seems like a no-brainer. The `bash` module was added to dracut in 2013 so we should not have any issues.
When I spun up a testbed, I noticed that the initramfs generated by my system also included the …
=> Explicitly require bash, blacklist dash

bin/generate-zbm, contrib/syslinux-update.sh
Support for syslinux is poorly tested and, in fact, still doesn't work properly. When `Components.Versions` is set to `false`, `generate-zbm` will properly roll `vmlinuz-bootmenu`, `initramfs-bootmenu.img` as well the backup files `vmlinux-bootmenu-backup` and `initramfs-bootmenu-backup.img`. However, the syslinux configuration generator doesn't build the proper backup entries. Although the backup entry has `KERNEL` line that points to `vmlinuz-bootmenu-backup` as expected, the `LABEL` for this entry is still `ZFSBootMenu-bootmenu` (the same as the entry for the newer `vmlinuz-bootmenu` entry) and, even worse, the `INITRD` points to `initramfs-bootmenu.img` in *both* entries. Not only will the entry *not* boot the known-good backup version, it is likely not to boot at all, since the …
=> generate-zbm: deprecate syslinux support

zfsbootmenu/lib/zfsbootmenu-lib.sh
After commit 3399f4bdc6ca, ZBM no longer allows user to select a kernel to boot, with the log error message:
```
ZFSBootMenu: kernel file zfsbootmenu/<pool and bootenv here>/kernels missing
```
That is due to that the path to the kernels list hasn't been updated to use `be_location()` and still uses the old `"zfsbootmenu/<pool>"` scheme. Doing `ln -s` from the recovery shell solves the problem.
Adjust that place accordingly to fix the issue.
=> Fix kernel selection after introducing $BASE/environments

zfsbootmenu/bin/zfsbootmenu, zfsbootmenu/bin/zlogtail, zfsbootmenu/install-helpers.sh, zfsbootmenu/lib/zfsbootmenu-lib.sh, zfsbootmenu/libexec/zfsbootmenu-help
`fzf` 0.35 introduced border/preview labels. Global (e.g. top row) text can now be set for any invocation of `fzf`. This means that we can now have a header that displays which screen you're on when in the main `zfsbootmenu` interface. The recovery shell and zdebug/trace screen, and any screens requiring custom input (cloning a snapshot, pool rollback, etc) do not have a header.
Included in this WIP are the following changes:
* Test if the border label option exists, gate it behind `HAS_BORDER_LABEL`
* Add a `draw_page`  (would `global_header` make more sense?) function that determines which page to highlight based on the name of the caller. Easy to extend / keep all of the logic central to one place.
* Changes the preview border from rounded to sharp, and then sets it to white. This now …
=> Use fzf border labels

bin/generate-zbm, etc/zfsbootmenu/config.yaml, testing/helpers/chroot-arch.sh, testing/helpers/zbm-populate.sh
If no command-line or configuration option to force one of dracut or mkinitcpio is specified, prefer dracut if the command is available and mkinitcpio otherwise.
=> Automatically select initramfs generator when not forced

zfsbootmenu/lib/zfsbootmenu-lib.sh
Swapping the vertical separators for horizontal and adding brackets around the chosen tab will make the selection visible even without color.
=> Make selected tab more distinctive in global header

zfsbootmenu/bin/zlogtail, zfsbootmenu/lib/zfsbootmenu-lib.sh, zfsbootmenu/libexec/zfsbootmenu-diff
`draw_diff` needs to be able to trap SIGINT to gracefully handle exiting when `zfs diff` blocks. It was mildly cleaned up to reflect that it's now a full-fledged script instead of a function call.
This highlighted that `global_header` was a bit sloppy in how it needed to detect the caller. I've switched it to use the basename of the calling script if the function is `main`.
=> Fix draw_diff not exiting correctly

docs/BUILD.md, dracut/module-setup.sh, initcpio/install/zfsbootmenu, releng/docker/README.md, releng/docker/build-init.sh, zbm-builder.sh
None of the `zpool import` instances actually use the cache file, so there is no value in including it in the initramfs.
I am also open to considering an alternative. The best alternative that I can think of wraps `zpool import` with a custom function along the lines of
```bash
import_zpool() {
if [ -s "/etc/zfs/zpool.cache" ]; then
zdebug "attempting 'zpool import' with cache file"
local output
if output="$(zpool import -c /etc/zfs/zpool.cache "$@")" && [ -n "${output}" ]; then
echo "${output}"
return 0
fi
zdebug "import failed with cache file, reattempting without cache"
fi
zpool import "$@"
}
```
Either we try to use the cache file if it's available, or we remove it. Do you have a preference?
=> Stop installing zpool.cache

bin/generate-zbm, docs/pod/generate-zbm.5.pod, releng/make-binary.sh
I broke make-binary.sh with recent changes to the build-container entrypoint. This should be resolved, but my changes need another set of eyes.
While I was at it, I added a `--showver` flag to `generate-zbm` that prints the program version and clarified that `--version` or `Global.Versions` only have meaning in versioned output products. The "Creating ZFSBootMenu" message now always uses the internal version string.
This addition allows us to run some of the releng scripts as, e.g.,
```sh
./releng/make-binary.sh "$(bin/generate-zbm --showver)"
```
Eventually, we can allow some of the releng scripts that need a version (but not `tag-release.sh`, because that has the responsibility of actually setting `$VERSION` in `generate-zbm`) to just call `bin/generate-zbm --showver` directly if no …
=> Improve version handling, restore functionality in make-binary.sh

testing/helpers/chroot-debian.sh, testing/helpers/chroot-ubuntu.sh, testing/helpers/install-debian.sh, testing/run.sh, testing/setup.sh
Adding a `-E` flag to `testing/setup.sh` allows us to pass environment variables to the image build process, which means we can parameterize releases and do all sorts of other good stuff. I tested a setup with
```sh
./setup.sh -a -o debian -E RELEASE=buster -D /tmp/debs
./setup.sh -i -x -o ubuntu -E RELEASE=kinetic -D /tmp/debs
```
and was greeted with a shockingly old Debian installation followed by a newer Ubuntu than we install by default.
While I was at it, I rethought how we choose initramfs generators, meaning things work as expected if `dracut` isn't locally installed.
=> testing: Allow environment customization, better choose initramfs generators

bin/generate-zbm, docs/pod/zfsbootmenu.7.pod, zfsbootmenu/hook/zfsbootmenu-parse-commandline.sh, zfsbootmenu/install-helpers.sh
With the removal of `skim` support, we no longer have a fuzzy finder for 64bit Big Endian systems. As such, there's no need to do any endianness checks in a few option paths.
#376 will need a minor bump to track the zfsbootmenu man page change.
=> deprecation: remove big endian checks

dracut/module-setup.sh, initcpio/install/zfsbootmenu, testing/helpers/image.sh, testing/setup.sh
Expand pool compatibility support in the testing framework. By default, `Debian` and `Ubuntu` test environments will use a pool compatibility of `openzfs-2.0-linux`, which lines up with the version available in the latest releases. The `POOL_COMPAT` environment variable can be manually set (or overridden in the case of the previous distributions) to any specific value.
Dracut and initcpio now also copy these files in to the ZBM image so that they can be read/used in the recovery shell.
=> Pool compatibility support in testing / built images

docs/CHANGELOG.md, testing/TPSReport.md
Lets get the v2.1.0 party started.
=> [WIP] Testing, review, documentation for v2.1.0

docs/guides/debian/uefi-install.rst
The existing Debian guide had stylistic and step variations that made it stand out compared to the Void guides. This is a first pass at normalizing it to that standard.
This work precedes #390, which introduces templated re-usable snippets. That PR will expand on the work done here and use as many repeatable `_includes` as possible.
* `rEFInd` has been stripped out because the package provided by Debian seems to be buggy.
* Encrypted/Unencrypted tabs for a choose-your-own-adventure are used
* More fat has been trimmed from the steps/explanations
=> Adapt Debian guide to follow Void install guide layouts

docs/guides/_include/efi-boot-check.rst, docs/guides/debian/single-disk-detached-uefi.rst, docs/guides/debian/single-disk-uefi.rst, docs/guides/void-linux/single-disk-detached-uefi.rst, docs/guides/void-linux/single-disk-uefi.rst
Neither `hrmpf` or the Debian live CDs mount `efivarfs` by default, so `efibootmgr` fails as an early check. Checking `dmesg` for that string seems to be a reliable check to differentiate BIOS vs EFI booting.
=> docs/guides/: change early EFI boot check

docs/guides/_include/configure-efibootmgr.rst, docs/guides/_include/efi-seealso.rst, docs/guides/debian/_include/efi-boot-method.rst, docs/guides/void-linux/_include/efi-boot-method.rst
`guides/general/portable` might need to be expanded to cover an ESP on a local disk as well as one on a USB drive.
=> docs/guides/: document additional EFI resources

docs/guides/_include/create-filesystems.rst, docs/guides/opensuse.rst, docs/guides/opensuse/_include/commandline.rst, docs/guides/opensuse/_include/distro-install.rst, docs/guides/opensuse/_include/efi-boot-method.rst, docs/guides/opensuse/_include/live-environment.rst, docs/guides/opensuse/_include/zbm-install-deps.rst, docs/guides/opensuse/_include/zbm-install.rst, docs/guides/opensuse/_include/zfs-config.rst, docs/guides/opensuse/uefi.rst, docs/index.rst
openSUSE Leap guide. Oof.
- Adds `udevadm trigger` to the global filesystem creation block, to be executed after zpool create.
=> docs/guides/opensuse/: Initial Leap 15.4 guides

docs/online/recovery-shell.rst, zfsbootmenu/bin/zfs-chroot, zfsbootmenu/help-files/132/recovery-shell.ansi, zfsbootmenu/help-files/52/recovery-shell.ansi, zfsbootmenu/help-files/92/recovery-shell.ansi, zfsbootmenu/lib/zfsbootmenu-completions.sh, zfsbootmenu/lib/zfsbootmenu-core.sh, zfsbootmenu/libexec/zfsbootmenu-init
`initcpio` mounts `efivarfs` as read-write, `dracut` doesn't mount it at all. Inside zfsbootmenu-init, we now check if the system is in EFI mode and then mount (or remount) `efivarfs` as read-only.
When chrooting into a boot environment, `efivarfs` is mounted in the chroot as read-only if the zpool is read-only, and read-write if the zpool is read-write.
When entering a recovery shell, `efivarfs` is re-mounted as read-write if `efibootmgr` is present in the initramfs. Exiting the shell remounts it as read-only.
=> zfsbootmenu: manage efivarfs when needed

docs/guides/_include/zgenhostid.rst, docs/guides/ubuntu.rst, docs/guides/ubuntu/_include/commandline.rst, docs/guides/ubuntu/_include/distro-install.rst, docs/guides/ubuntu/_include/efi-boot-method.rst, docs/guides/ubuntu/_include/live-environment.rst, docs/guides/ubuntu/_include/zbm-install-deps.rst, docs/guides/ubuntu/_include/zbm-install.rst, docs/guides/ubuntu/_include/zfs-config.rst, docs/guides/ubuntu/uefi.rst, docs/index.rst
As per title. 
The guide is almost identical to Debian's, with some changes:
* Remove dkms related instructions throughout as Ubuntu's kernel comes with ZFS modules already available
* Different installation environment instructions (using Ubuntu desktop's live installation media)
* Different apt sources
* Debootstrap
* Other ubuntu-specific instructions
Tested (qemu/kvm):
* Encrypted: with and without refind
* Non-encrypted: with and without refind
* ZFSBootMenu installation from sources
=> Add Ubuntu 22.04 installation instructions

docs/guides/_include/create-filesystems.rst, docs/guides/alpine.rst, docs/guides/alpine/_include/cleanup.rst, docs/guides/alpine/_include/commandline.rst, docs/guides/alpine/_include/distro-install.rst, docs/guides/alpine/_include/efi-boot-method.rst, docs/guides/alpine/_include/live-environment.rst, docs/guides/alpine/_include/setup-esp.rst, docs/guides/alpine/_include/zbm-install.rst, docs/guides/alpine/_include/zfs-config.rst, docs/guides/alpine/uefi.rst, docs/index.rst
I know very little about Alpine. This guide was created by merging the steps in:
* [OpenZFS Alpine install guide](https://openzfs.github.io/openzfs-docs/Getting%20Started/Alpine%20Linux/Root%20on%20ZFS/1-preparation.html)
* [testing/helpers/install-alpine.sh](https://github.com/zbm-dev/zfsbootmenu/blob/master/testing/helpers/install-alpine.sh)
* [testing/helpers/chroot-alpine.sh](https://github.com/zbm-dev/zfsbootmenu/blob/master/testing/helpers/chroot-alpine.sh)
=> docs/guides/alpine/: initial Alpine guide

docs/guides/_include/pool-creation.rst, docs/guides/alpine/_include/distro-install.rst, docs/guides/alpine/_include/zfs-config.rst, docs/guides/debian/_include/distro-install.rst, docs/guides/fedora/_include/distro-install.rst, docs/guides/opensuse/_include/distro-install.rst, docs/guides/ubuntu/_include/distro-install.rst, docs/guides/void-linux/_include/distro-install.rst
There's little benefit to setting a zpool cache file for common root-on-ZFS systems. There are benefits on systems with many disks, but those that need it can set it up. For the rest of us, it's just something that can cause headaches.
=> docs: remove zpool.cache usage

docs/online/recovery-shell.rst, releng/rst2help.sh, zfsbootmenu/bin/zfsbootmenu, zfsbootmenu/bin/zsnapshots, zfsbootmenu/help-files/132/recovery-shell.ansi, zfsbootmenu/help-files/52/recovery-shell.ansi, zfsbootmenu/help-files/92/recovery-shell.ansi, zfsbootmenu/lib/fzf-defaults.sh, zfsbootmenu/lib/zfsbootmenu-completions.sh, zfsbootmenu/lib/zfsbootmenu-core.sh, zfsbootmenu/libexec/zfsbootmenu-preview
In the event that no boot environments with a valid /boot are found, recovery might be as simple as interacting with an older snapshot. The recovery shell tool `zsnapshot` attempts to make that easier by allowing access to the main snapshot interface for a given dataset.
fzf defaults suitable for the main interfaces were moved to a lib file that can be sourced. These defaults allow smaller tools to match the same behavior that fzf has when invoked from /bin/zfsbootmenu .
select_kernel now returns 1 when the 'kernels' file for a boot environment can't be found, with nothing printed. The caller is expected to handle that condition accordingly.
Fixes #418
=> zsnapshot: recovery environment helper tool

zfsbootmenu/lib/zfsbootmenu-lib.sh
Root datasets should never be automatically mounted. Anything that is considered a root dataset (regardless of a valid kernel/initramfs pair being present) should be checked for `canmount=on` being set. If it is, throw up a zwarn() . This possibly needs to be more aggressively warned via a timed_prompt - forcing user interaction.
=> zfsbootmenu: warn when canmount=on is set for root dataset

zfsbootmenu/bin/zfs-chroot
When entering a chroot for a regular dataset and the pool is read-only, provide a timed_prompt that lets the user choose between entering a read-only chroot (return key/enter key) or a read-write chroot (escape key). If the dataset is a snapshot or the pool is already read-write, do not show the prompt.
Fixes #428
=> zfs-chroot: add read-write prompt

docs/guides/debian.rst, docs/guides/debian/_include/bookworm/distro-install.rst, docs/guides/debian/_include/bookworm/live-environment.rst, docs/guides/debian/_include/bullseye/distro-install.rst, docs/guides/debian/_include/bullseye/live-environment.rst, docs/guides/debian/bookworm-uefi.rst, docs/guides/debian/bullseye-uefi.rst
Prepare for the upcoming Debian 12 (Bookworm) release by adding a guide for it. Links for CD Images in both the Bullseye and Bookworm guides need to be fixed so that they point to the right resources after Debian 12 is officially released.
We can possibly create links for Bullseye images to some persistent directory at https://cdimage.debian.org/mirror/cdimage/archive/ . I'll need to poke around the cdimage.debian.org in more detail to find a stable URL, though.
Closes #425
=> docs/guides/debian/: add initial bookworm guide

docs/guides/general.rst, docs/guides/general/container-example.rst, docs/guides/general/mkinitcpio.rst, docs/guides/general/remote-access.rst
- docs/guides/general: move mkinitcpio setup to its own guide
- docs/guides/general/remote-access: refactor for easier reading
hopefully this reads better than the old guide. made some stuff consistent between dracut and mkinitcpio to make organisation easier
=> refactor remote access guide

releng/tag-release.sh
This makes release tagging more flexible, allowing us to act on branches that apparently track the series for which we are tagging a release.
=> releng/tag-release.sh: relax branch requirement

etc/zfsbootmenu/recovery.conf.d/recovery.conf, releng/docker/Dockerfile, releng/docker/image-build.sh
Apparently `cryptsetup` is unusable without `dm-crypt` (#468), so it should be added.
While we're at it, it's time to migrate to a newer base image.
=> Add dm-crypt kernel module to recovery images

zfsbootmenu/bin/zlogtail, zfsbootmenu/lib/kmsg-log-lib.sh, zfsbootmenu/lib/zfsbootmenu-core.sh, zfsbootmenu/libexec/zfsbootmenu-init
Before landing at the emergency_shell in the main import loop, log the output of a failed zpool import for every pool that's marked UNAVAIL .
In the emergency_shell function, write any log messages at the 'err' level directly to the active console.
https://asciinema.org/a/5QLE1dKHyeMDdmGQNmjM29yU0
=> zfsbootmenu: log errors for unimportable pools

dracut/module-setup.sh, etc/zfsbootmenu/release.conf.d/common.conf, zfsbootmenu/install-helpers.sh, zfsbootmenu/lib/zfsbootmenu-core.sh
The default behavior of hostid matching is useful to have on in binary releases. However, it generates a warning message that isn't really relevant for users of that build.
It's expected that the spl_hostid value in ZFSBootMenu.EFI won't match the local pool hostid - advising these users to manually set `spl_hostid` on the ZBM KCL runs counter to how we recommend ZBM should be used.
=> zfsbootmenu-core: conditionally disable spl_hostid warnings

testing/rollup.pl, testing/run.sh, zfsbootmenu/profiling/profiling-lib.sh
See where the function is in the source tree: https://somebits.link/u/p/5148e31b8d/flamechart.svg
Flamegraphs are unchanged: https://somebits.link/u/p/902469ec98/flamegraph.svg
=> testing: add function line numbers to flamecharts

zfsbootmenu/lib/zfsbootmenu-core.sh
Walking through a four-level loop to find all possible initramfs images can be painful, and most times the distribution default will be in place. Let's front-load the initramfs search with commonly expected formats for popular distributions and avoid some of the pain of the complex but more exhaustive loop.
=> zfsbootmenu-core: optimize initramfs search

contrib/keycache.sh, zfsbootmenu/bin/zfsbootmenu, zfsbootmenu/bin/zlogtail, zfsbootmenu/bin/zsnapshots, zfsbootmenu/lib/zfsbootmenu-ui.sh, zfsbootmenu/libexec/zfsbootmenu-diff, zfsbootmenu/libexec/zfsbootmenu-help, zfsbootmenu/libexec/zfunc
Rename zfsbootmenu-lib to zfsbootmenu-ui-lib to more accurately represent which functions are contained therein.
Additionally, normalize how libraries are sourced.
=> zfsbootmenu: rename UI library, normalize imports

.gitattributes
this prevents them from showing in Github diffs by default
https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
=> .gitattributes: treat help files and manpages as generated

bin/generate-zbm
This is a direct clone of the process/steps used by `mkinitcpio`. It's been tested locally with the Gummiboot stub and the most recent stub available on Arch; both are able to boot a test VM. Pending further review, I'll clean up the commits and add a larger degree of comments on what is happening. There's been minimal error handling added to this.
Comments/testing/nits welcome.
Closes #503
=> bin/generate-zbm: use objcopy procedure from mkinitcpio

docs/guides/_include/configure-efibootmgr.rst, docs/guides/general/uefi-booting.rst
should be slightly more foolproof
=> docs/guides: quote efibootmgr paths instead of escaping

Makefile, examples/kboot.conf, examples/syslinux.cfg
Remove kboot.conf, this was primarily used when POWER9/petitboot was still being targeted. Update syslinux.cfg to demonstrate how to boot fixed name files. Install examples/ via Makefile.
=> examples: modernize, install

zfsbootmenu/lib/zfsbootmenu-core.sh
Block cloning in ZFS 2.2.0 is dangerous. Until it stabilizes, we should disable it if the tuneable to do so is available when a pool is set read/write.
See https://github.com/openzfs/zfs/pull/15529 for more details.
I don't think we need to expose this as a toggleable option. This feature should be simple and not plumbed very deeply, on the hope that it's just a short-term patch for an unlikely source of problems for people. If users really care, they can turn it back on before doing whatever it is they're going to do in the recovery shell.
=> zfsbootmenu-core: disable block cloning for R/W pools

zfsbootmenu/lib/zfsbootmenu-core.sh
this currently appears to mostly or fully mitigate the silent corruption bug that was originally thought to be caused by block cloning. Keeping bclone disabled for now as it is a common avenue for triggering the bug, despite not being the root cause.
see openzfs/zfs#15526
=> zfsbootmenu-core: disable zfs_dmu_offset_next_sync for R/W pools

zfsbootmenu/lib/zfsbootmenu-core.sh, zfsbootmenu/libexec/zfsbootmenu-help
What it says on the tin. Make the system report easier to access, add some color/spice to the output. Since everything is generated live, there's no "clean" line wrapping. The fzf preview window does at least wrap long lines, however.
=> Use zbm-release file, add some color to zreport

releng/make-commit-log.sh
There's probably a better way to do this ... but this seems to work.
`releng/make-commit-log.sh -r v2.2.x -t v2.2.0`
=> releng: add hacky commit log generator

docs/guides/third-party.rst
Install scripts are liable to become outdated w/r/t our recommended practices, especially when they aren't written by us and the author lets them sit.
It's not hard to install ZBM from a guide, and users can create their own script based on those guides by just copying/adapting the codeblocks.
Not much is lost from removing these, as Void and Ubuntu have official install guides, and Arch has proper documentation linked on the Arch wiki.
=> docs/guides/third-party: remove install scripts

zfsbootmenu/lib/zfsbootmenu-core.sh
I realized tonight that the hooks in the pre-built initramfs might not be very discoverable. Showing them in zreport (now exposed in the Help system) might improve that a bit.
=> zfsbootmenu-core: show enabled/disabled hooks in zreport

zfsbootmenu/bin/zsnapshots, zfsbootmenu/lib/zfsbootmenu-core.sh
`zsnapshots` is used from the recovery shell, and as such it accepts any input from the user.  Attempt minimal validation that the filesystem name is actually a ZFS _filesystem_ . Errors are logged via zerror, to work in tandem with on-going work to print zerror logs to recovery shell.
=> zsnapshots: check if input is a valid ZFS filesystem

docs/online/recovery-shell.rst, etc/zfsbootmenu/release.conf.d/common.conf, zfsbootmenu/bin/mount_esp, zfsbootmenu/help-files/132/recovery-shell.ansi, zfsbootmenu/help-files/52/recovery-shell.ansi, zfsbootmenu/help-files/92/recovery-shell.ansi, zfsbootmenu/install-helpers.sh, zfsbootmenu/lib/zfsbootmenu-completions.sh, zfsbootmenu/lib/zfsbootmenu-core.sh
Add a `mount_esp` function that mounts `/dev/sdxY` at `/mnt/sdxY` if nothing else is mounted there. If the device is already mounted, return the mountpoint. The shell completion helper only completes unmounted ESP devices.
Unmounting the device is left as an exercise to the user.  I'm interested in a reasonable argument for handling this when exiting the recovery shell, like we do for ZFS datasets.
The mount operation is possibly going to be a problem. I'm trapping errors and dumping them to the console, but that's not super graceful.
Edit:
Thinking about this more, I should log all errors via `zerror` and then add something to the recovery shell prompt that evaluates if `has_errors` is set - if it is, dump the errors to the console and then clear the flag. This lets internal functions …
=> recovery shell: ESP mount helper and tab completion

zfsbootmenu/bin/logs, zfsbootmenu/install-helpers.sh, zfsbootmenu/lib/kmsg-log-lib.sh, zfsbootmenu/libexec/recovery-error-printer
I'm not super happy with how `print_kmsg_logs` is shaking out, but there's only so much time I'm willing to spend chasing elegance.
This is modestly tested, and could likely use further refinement after people play with it.
=> recovery shell: print zerrors since the last command was executed

docs/guides/_include/pool-creation.rst
With ZFSBootMenu binary releases shipping with OpenZFS 2.2.x, we can bump the minimum pool compatibility recommend.  Debian will need to be special cased. _Again_.  I'm open to suggestions on what to do here - maybe we just stop setting pool option at all?
=> docs/guides/: update pool compat to openzfs-2.2

docs/man/zfsbootmenu.7.rst, zfsbootmenu/libexec/zfsbootmenu-init, zfsbootmenu/pre-init/zfsbootmenu-parse-commandline.sh, zfsbootmenu/pre-init/zfsbootmenu-preinit.sh
With keyfiles being stored on USB drives, the boot process can be non-deterministic due to intermittently missing /dev entries. Users can now provide one or more devices that must be present before the pool import process can start. Unlike dracut, you can simply hit the escape key to cancel this check.
=> zfsbootmenu: add zbm.waitfor argument handler

releng/make-binary.sh
Needs testing and backporting to v2.3.x before another release is tagged, but this ensures that we create images during releng that will build the release that is being tagged.
=> releng/make-binary.sh: specify release tag in builder images by default

zfsbootmenu/bin/zfsbootmenu
Rather than relying to a call to draw_be to determine if the bootenvs file is empty, the main loop should use the return code of populate_be_list to determine if any boot environments were found.
The sanity checks in draw_be are still present.
=> zfsbootmenu: clean up main loop

docs/guides/_include/recovery.rst, docs/guides/_include/release.rst, docs/guides/binary-releases.rst, docs/index.rst, releng/tag-release.sh, releng/update-includes.sh
Adds a minimal bit of documentation on release/recovery images. 
Closes #398
=> docs: binary releases helper/documentation

zfsbootmenu/bin/zsnapshots, zfsbootmenu/lib/zfsbootmenu-ui.sh
A couple of points:
- There is some duplication of `fzf` arguments with `draw_be`, but I'm not sure how hard we want to try to unify those two.
- To get proper ANSI coloring of the `border-label`, I needed to define `fs_header`; no amount of quoting magic allowed me to specify the header string inline and have color rather than seeing the raw ANSI escape sequence.
=> zsnapshots: allow filesystem selection when no argument is specified

releng/version.sh
1. Correct typo: --abbrev-rev -> --abbrev-ref
2. Limit repository search to the current directory
Fixes: #588.
To reproduce the issue fixed by (2) and confirm the fix, do something like
```sh
cd $XBPS_DISTDIR
mkdir test
cd test
curl -L https://github.com/zbm-dev/zfsbootmenu/archive/v2.3.0.tar.gz | tar -zxvf -
( cd zfsbootmenu-2.3.0 && make show-version )
curl -L https://github.com/zbm-dev/zfsbootmenu/archive/git-er-done.tar.gz | tar -zxvf -
( cd zfsbootmenu-git-er-done && make show-version )
```
=> releng/version.sh: fix git-based version detection

docs/guides/chimera.rst, docs/guides/chimera/_include/cleanup.rst, docs/guides/chimera/_include/commandline.rst, docs/guides/chimera/_include/distro-install.rst, docs/guides/chimera/_include/efi-boot-check.rst, docs/guides/chimera/_include/efi-boot-method.rst, docs/guides/chimera/_include/live-environment.rst, docs/guides/chimera/_include/os-release.rst, docs/guides/chimera/_include/post-installation.rst, docs/guides/chimera/_include/zbm-install.rst, docs/guides/chimera/_include/zfs-config.rst, docs/guides/chimera/uefi.rst, docs/index.rst
What it says on the tin. A basic root-on-ZFS for Chimera, using an LTS kernel and a prebuilt release asset.  There's no `initramfs-tools` hook to copy key files into an initramfs, so the one used in the `testing/` framework was dropped in.
Both the unencrypted / encrypted choose your own adventure were followed via copy-pasting into a terminal. In both cases, I was able to boot the system.
=> docs/guides/chimera/: initial Chimera guide

zfsbootmenu/bin/zfsbootmenu, zfsbootmenu/init.d/10-kmods, zfsbootmenu/init.d/20-hostid, zfsbootmenu/init.d/30-device-wait, zfsbootmenu/init.d/40-early-hooks, zfsbootmenu/init.d/50-import-pools, zfsbootmenu/install-helpers.sh, zfsbootmenu/lib/zfsbootmenu-core.sh, zfsbootmenu/libexec/zfsbootmenu-init, zfsbootmenu/libexec/zfsbootmenu-run-hooks, zfsbootmenu/pre-init/zfsbootmenu-preinit.sh
This is an attempt to overcome issues like https://github.com/zbm-dev/zfsbootmenu/discussions/597, where the console blocks waiting for user input and leaves ZFSBootMenu uninitialized for remote logins. Initialization is broken into several functional units, and each is executed and then marked non-executable so that subsequent calls to `zfsbootmenu-init` will not attempt to run them again. Similarly, early-setup hooks, which are expected to run exactly once, will be marked non-executable after being run the first time for more granularity among these user-configurable components.
Because `zfsbootmenu-init` is now (more or less) idempotent, `/bin/zfsbootmenu` can attempt to run it if necessary rather than just spinning forever.
=> init: split initialization into quasi-idempotent parts

zfsbootmenu/install-helpers.sh
When installing symlinks into their initramfs images, both dracut and mkinitcpio attempt to canonicalize symlink targets, copying the resolved target into place and making a new symlink that points to there. This means that, even when building a local image, symlinks like `poweroff` and `zbm` will point copies of scripts in `/usr/lib/zfsbootmenu/bin` rather than the versions already installed into `/usr/bin`. For container builds or those built from custom installations that override `$zfsbootmenu_module_root`, the target paths get even weirder in the initramfs image. It's also problematic, because people doing testing may attempt to modify things like `/usr/bin/zfsbootmenu` *in situ* and be surprised when they run `zbm` and get a *different* copy of the script than the one they modified. …
=> zfsbootmenu/install-helpers.sh: preserve relative symlinks

docs/man/zfsbootmenu.7.rst
Renamed the `#zfs-properties` link so that it's more precise now that there's a pool property. Open to changes to the language, it seems a bit inelegant.
=> docs/man/zfsbootmenu: document bootfs pool property

docs/guides/alpine/_include/zfs-config.rst
Add zfs-scripts to packages installed. It is listed when setting up live environment but missing here. This leads to zpool errors after installation because /usr/share/zfs/compatibility.d is missing.
=> docs/guides/alpine/: add zfs-scripts to packages installed

releng/docker/build-init.sh
This is an alternative to #675 that refactors some of the update flow:
1. Multiple `-u` options no longer trigger special behavior. It always makes sense to skip kernel and ZFS upgrades with `-u`, because we don't have the headers available to rebuild kmods in either case.
2. A singleton `update_xbps` can be run multiple times without re-fetching the package index or trying to update `xbps`.
3. A new `-k` argument allows simple specification of a single kernel series for use in the image:
- This will trigger the installation of `dkms`, the kernel package and its headers
- A default override in `config.yaml` is created to match the specified series (this is added to the YAML overrides first, so users can explicitly override it again)
4. A new `-z` argument will trigger a ZFS update iff a …
=> releng/docker/build-init.sh: make it easier to customize kernel versions

testing/Makefile
I don't setup a new system often, but when I do I completely forget what the `testing/` run-time requirements are.
=> testing/: add Makefile to install Void deps

zfsbootmenu/lib/zfsbootmenu-core.sh
Attempt to detect if ZBM is built on top of Dracut or mkinitcpio, show that in `zreport`.
=> lib/zfsbootmenu-core.sh: add initramfs generator to zreport

zfsbootmenu/init.d/50-import-pools
Binary release users shouldn't be told to generate a new ZBM image.
=> init.d/50-import-pools: tailor text if using a binary release

etc/zfsbootmenu/dracut.conf.d/zfsbootmenu.conf
On Void, and possibly other distributions, /bin/sh points to /bin/dash. When no specific shell module (bash, dash, busybox) is requested, the system /bin/sh is used by default. Because ZFSBootMenu blacklists dash, shell-interpreter is unable to be installed, which then blocks multiple other key/core dracut modules.
Fixes #690
=> dracut: explicitly require the bash module

bin/generate-zbm, docs/general/uefi-booting.rst, docs/man/generate-zbm.5.rst
gummiboot doesn't work with newer (6.6+?) kernels, so lets stop recommending it as a default. If you still want to use it, set EFI.Stub in your configuration file.
The testing scripts still reference the old gummiboot location as a fall back, but that's not unreasonable that we leave that in our testing infra.
=> bin/generate-zbm: remove gummiboot from default stub list

releng/make-binary.sh, releng/tag-release.sh
We have multiple kernels in the build image, so we might as well spit out ZBM images for each one. Tested (for basic image production, not that the images are actually function) with
./releng/make-binary.sh v3.0.0 ghcr.io/zbm-dev/zbm-builder:development
=> releng/make-binary.sh: build images for all installed kernels

zfsbootmenu/lib/zfsbootmenu-core.sh, zfsbootmenu/libexec/zfsbootmenu-run-hooks
The hook report section uses `+x` to know if a hook is enabled - run once hooks lose `+x` after completion. Append `.completed` to the hook file name, and then do some trickery based on that in `zreport`.
=> zreport: handle hooks that run once and are completed

zfsbootmenu/bin/zfsbootmenu, zfsbootmenu/lib/zfsbootmenu-core.sh
bin/zfsbootmenu cheats and passes a timeout of 0 seconds, which is an instant timeout / success. Protect that value and restrict infinite timeouts to negative numbers entirely.
This fixes `zbm.skip`.
=> zfsbootmenu-core.sh: fix instant timed prompts

releng/sign-assets.sh
If you store your passphrases somewhere else (Vaultwarden, etc), this provides a reasonable way to get them into the signing process.
=> sign-assets.sh: add manual passphrase input option

docs/general/container-building/example.rst
In the container build, copy the contents of the dropbear folder into the expected folder instead of symlinking as the mkinitcpio function `add_full_dir` does not handle symlinked folders properly
Full discussion in https://github.com/zbm-dev/zfsbootmenu/discussions/724
Also fix quick typo: missing quote
=> docs: copy dropbear keys and config instead of symlink

bin/generate-zbm, docs/man/generate-zbm.5.rst, docs/man/zfsbootmenu.7.rst, zfsbootmenu/lib/zfsbootmenu-core.sh
generate-zbm now understands the `EFI.DeviceTree` key. This key can contain one of three possible values:
1) /absolute/path/%{kernel}/to/device-tree-file.dtb 
2) /absolute/path/to/device-tree-file.dtb
3) partial/path/device-tree-file.dtb
If found, %{kernel} is replaced with the kernel version being built in to the EFI asset. Partial paths are appended to `/boot/dtbs/dtb-$kernel/`, a well-known path for device tree files used by Void Linux.
Inside ZFSBootMenu, the `org.zfsbootmenu:devicetree` property is read. The values of this property are handled in the same order/priority as `EFI.DeviceTree`.
Documentation will be written and appended to this PR once the overall design of this support is accepted.
=> aarch64 support: efi stub and devicetree selection

docs/general/container-building/example.rst
It seems the initially community provided xhci-teardown script was later incorporated into the system in 2.3.0 per https://github.com/zbm-dev/zfsbootmenu/commit/ff5956298ab103b654606f6cfefc7c5343124926 and no longer requires manual enabling.
This PR removes the instructions for manually enabling the now obsolete hook.
=> Remove obsolete section on xhci-teardown from docs

zfsbootmenu/bin/zfs-chroot
Instead of manually tracking everything mounted under the chroot, check mounts and sort the list by the directory depth. Given directory depths of 10,9,8, assume that any directories at the same depth can be unmounted in any order.
=> zfs-chroot: unmount everything under chroot mountpoint

docs/general/remote-access.rst
As discussed on IRC, fixes the instructions for key creation for dracut-crypt-ssh module, preserving the instructions for mkinitcpio
=> docs: dracut-crypt-ssh keys name and format fix

docs/guides/_include/pool-creation.rst
With OpenZFS 2.2 as the current LTS, lets set our minimum pool feature set to that release. All distros we have guides for should be on at least that version by now.
=> docs/guides/: recommend openzfs-2.2-linux pool compatibility

testing/run.sh, zfsbootmenu/libexec/zfsbootmenu-diff
CI/CD uses 0.11.0, Void is still on 0.10.0. Shellcheck doesn't seem to understand coprocs.
=> shellcheck: fix warnings from 0.11.0

docs/man/zfsbootmenu.7.rst, zfsbootmenu/init.d/50-import-pools, zfsbootmenu/pre-init/zfsbootmenu-parse-commandline.sh, zfsbootmenu/pre-init/zfsbootmenu-preinit.sh
Other bootloaders, such as `rEFInd`, can now be used to drive the boot process by specifying a dataset from which to boot. `zbm.prefer` now accepts a full dataset path, with the previous `!` and `!!` modifiers still applying to the pool portion of the dataset.
This closes https://github.com/zbm-dev/zfsbootmenu/discussions/738
=> zfsbootmenu: extend zbm.prefer to set bootfs
